const SET_ROUTES = 'SET_ROUTES';

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
const SET_SIZE = 'SET_SIZE'

const ADD_VISITED_VIEW = 'ADD_VISITED_VIEW'
const ADD_CACHED_VIEW = 'ADD_CACHED_VIEW'
const DEL_VISITED_VIEW = 'DEL_VISITED_VIEW'
const DEL_CACHED_VIEW = 'DEL_CACHED_VIEW'
const DEL_OTHERS_VISITED_VIEWS = 'DEL_OTHERS_VISITED_VIEWS'
const DEL_OTHERS_CACHED_VIEWS = 'DEL_OTHERS_CACHED_VIEWS'
const DEL_ALL_VISITED_VIEWS = 'DEL_ALL_VISITED_VIEWS'
const DEL_ALL_CACHED_VIEWS = 'DEL_ALL_CACHED_VIEWS'
const UPDATE_VISITED_VIEW = 'UPDATE_VISITED_VIEW'

const CHANGE_SETTING = 'CHANGE_SETTING'

const ADD_ERROR_LOG = 'ADD_ERROR_LOG'
const CLEAR_ERROR_LOG = 'CLEAR_ERROR_LOG'

export {
  SET_ROUTES,
  TOGGLE_SIDEBAR,
  CLOSE_SIDEBAR,
  TOGGLE_DEVICE,
  SET_SIZE,
  ADD_VISITED_VIEW,
  ADD_CACHED_VIEW,
  DEL_VISITED_VIEW,
  DEL_CACHED_VIEW,
  DEL_OTHERS_VISITED_VIEWS,
  DEL_OTHERS_CACHED_VIEWS,
  DEL_ALL_VISITED_VIEWS,
  DEL_ALL_CACHED_VIEWS,
  UPDATE_VISITED_VIEW,
  CHANGE_SETTING,
  ADD_ERROR_LOG,
  CLEAR_ERROR_LOG
}
